advertisers = [
    ('Buick','Buick'),
    ('Cadillac','Cadillac'),
    ('Chevrolet','Chevrolet'),
    ('GM', 'GM'),
    ('GM Accessories', 'GM Acessories'),
    ('GMC','GMC'),
    ('Holden','Holden'),
    ('Opel','Opel'),
    ('Opel Car Unity', 'Opel Car Unity'),
    ('Test', 'Test'),
    ('Vauxhall', 'Vauxhall')
]

markets = [
    ('US','US'),
    ('CA','CA'),
    ('MX','MX'),
    ('AT','AT'),
    ('AZ','AZ'),
    ('BA','BA'),
    ('BE','BE'),
    ('BG','BG'),
    ('BY','BY'),
    ('CH','CH'),
    ('CY','CY'),
    ('CZ','CZ'),
    ('DE','DE'),
    ('DK','DK'),
    ('EE','EE'),
    ('ES','ES'),
    ('FI','FI'),
    ('FR','FR'),
    ('GB','GB'),
    ('GE','GE'),
    ('GME','GME'),
    ('GR','GR'),
    ('HR','HR'),
    ('HU','HU'),
    ('IE','IE'),
    ('IL','IL'),
    ('IS','IS'),
    ('IT','IT'),
    ('KZ','KZ'),
    ('LT','LT'),
    ('LU','LU'),
    ('LV','LV'),
    ('MD','MD'),
    ('MK','MK'),
    ('MT','MT'),
    ('NL','NL'),
    ('NO','NO'),
    ('PL','PL'),
    ('PT','PT'),
    ('RO','RO'),
    ('RS','RS'),
    ('SE','SE'),
    ('SI','SI'),
    ('SK','SK'),
    ('TR','TR'),
    ('UA','UA'),
    ('AR','AR'),
    ('BR','BR'),
    ('CL','CL'),
    ('CO','CO'),
    ('EC','EC'),
    ('PE','PE'),
    ('PY','PY'),
    ('UY','UY'),
    ('VE','VE'),
    ('AU','AU'),
    ('ID','ID'),
    ('IN','IN'),
    ('MEO','MEO'),
    ('JP','JP'),
    ('KR','KR'),
    ('RU','RU'),
    ('VN','VN'),
    ('TH','TH'),
    ('ZA','ZA')
]

kpis = [
    ('Accessories','Accessories'),
    ('Apply For Credit','Apply For Credit'),
    ('Click to Chat - Live Chat','Click to Chat - Live Chat'),
    ('Click To Chat - Live Chat - Send Message','Click To Chat - Live Chat - Send Message'),
    ('Click To Chat - Pre-Chat Form','Click To Chat - Pre-Chat Form'),
    ('Competitive Comparison','Competitive Comparison'),
    ('Configurator - Complete','Configurator - Complete'),
    ('Configurator - Start','Configurator - Start'),
    ('Configurator - Engagement','Configurator - Engagement'),
    ('Current Offers','Current Offers'),
    ('Current Offers - View Offers','Current Offers - View Offers'),
    ('Download A Brochure','Download A Brochure'),
    ('Estimate Payments','Estimate Payments'),
    ('Estimate Payments - Complete','Estimate Payments - Complete'),
    ('Estimate Payments - Start','Estimate Payments - Start'),
    ('Homepage','Homepage'),
    ('Locate A Dealer','Locate A Dealer'),
    ('Locate A Dealer - Complete','Locate A Dealer - Complete'),
    ('Locate A Dealer - Start','Locate A Dealer - Start'),
    ('Locate A Vehicle - Complete','Locate A Vehicle - Complete'),
    ('Locate A Vehicle - Start','Locate A Vehicle - Start'),
    ('Locate A Vehicle - Vehicle Details','Locate A Vehicle - Vehicle Details'),
    ('Model Overview','Model Overview'),
    ('Model Overview - Colors', 'Model Overview - Colors'),
    ('Model Overview - Image Carousel','Model Overview - Image Carousel'),
    ('Model Overview - Sticky Navigation','Model Overview - Sticky Navigation'),
    ('One Minute Engagement','One Minute Engagement'),
    ('Photos','Photos'),
    ('Gallery','Gallery'),
    ('Request A Quote - Complete','Request A Quote - Complete'),
    ('Request A Quote - Start','Request A Quote - Start'),
    ('Request A Test Drive - Complete','Request A Test Drive - Complete'),
    ('Request A Test Drive - Start','Request A Test Drive - Start'),
    ('Specifications','Specifications'),
    ('Custom','Custom')
]

devices = [
    ('D','D'),
    ('M','M'),
    ('R','R')
]

u_variables = [
    ('U2', 'U2'),
    ('U3', 'U3'),
    ('U4', 'U4'),
    ('U5', 'U5'),
    ('U6', 'U6'),
    ('U7', 'U7'),
    ('U8', 'U8'),
    ('U9', 'U9'),
    ('U10', 'U10'),
    ('U11', 'U11'),
    ('U12', 'U12'),
    ('U13', 'U13'),
    ('U14', 'U14'),
    ('U21', 'U21'),
    ('U22', 'U22'),
    ('U23', 'U23'),
    ('U24', 'U24'),
    ('U26', 'U26')
]

kpis_plus = [('All','All')] + kpis
uvars_plus = [('None','None')] + u_variables

logical = [
    ('AND','AND'),
    ('OR','OR')
]
